CREATE SCHEMA subidapunto_bd;
USE subidapunto_bd;

CREATE TABLE usuarios(
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) UNIQUE,
    correo VARCHAR(40) UNIQUE,
    contrasenia VARCHAR(255)
);

CREATE TABLE autor(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100)
);

CREATE TABLE mangas(
	id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100),
    id_autor INT,
    capitulos INT,
    volumenes INT,
    score INT,
	CONSTRAINT FK_MANGA_AUTOR FOREIGN KEY (id_autor) REFERENCES autor(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE coleccion(
	id_usuario INT,
	id_manga INT,
    fecha_conseguida DATE,
	CONSTRAINT FK_COLECCION_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_COLECCION_MANGA FOREIGN KEY (id_manga) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE favoritos(
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT,
    id_manga INT,
    CONSTRAINT FK_FAVORITO_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_FAVORITO_MANGA FOREIGN KEY (id_manga) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);